---
additional_packages:
  - hyprland
  - neovim
  - tmux
  - alacritty
  - cilium-cli
  - waybar

packages: "{{ default_packages + additional_packages }}"

additional_service_packages: []
service_packages: "{{ default_service_packages + additional_service_packages }}"

